### ISSUE TITLE
EG 0.5 Support

### ISSUE THREAD

**Issue by paulo-lima-dev** [RedsGT/egSamsungTV#1]
Any chance this could be updated to EG 0.5.0-rc4.
This uses python 2.6 and EG 0.5.0 uses 2.7 so there is some issues

**Comment by RedsGT** [comment]
Most likely the issues are with samsungctl.  I can't remember if I back ported it or forward ported it to v2.6.  Can you try using samsungctl from the link in the readme and see if it works for you?

**Comment by paulo-lima-dev** [comment]
Sorry for taking so long to respond.
Is not working properly either.

EG 0.5.0 uses pyton 2.7
samsungctl uses pyton 3.0

I'm getting errors:
`Samsung TV (IP) 2016+: KEY_POWER
   Erro na ação: "Samsung TV (IP) 2016+: KEY_POWER"
   Traceback (most recent call last) (0.5.0-rc4):
     File "C:\Program Files (x86)\EventGhost\eg\Classes\ActionBase.py", line 116, in CallWrapper
       return self(*args)
     File "C:\ProgramData\EventGhost\plugins\egSamsungTV-master\__init__.py", line 472, in __call__
       with samsungctl.Remote(config) as remote:
     File "C:\ProgramData\EventGhost\plugins\egSamsungTV-master\samsungctl\remote.py", line 11, in __init__
       self.remote = RemoteWebsocket(config)
     File "C:\ProgramData\EventGhost\plugins\egSamsungTV-master\samsungctl\remote_websocket.py", line 28, in __init__
       self.connection = websocket.create_connection(url, config["timeout"])
   AttributeError: 'module' object has no attribute 'create_connection'`

The only action I manage to make it work on EG 0.5.0 is "Samsung TV (IP) 2016+: TurnOn"
